baseURL: ""
languageCode: en-us
title: World Civilisations



theme : hugo-theme-chunky-poster #lightbi-hugo # beautifulhugo # REPLACE WITH lightbi-hugo !
params:
    bigimg :  /2.jpg
    homeTitle: Discover the past 
    subtitle: ... and have fun in the process.
    



menu:
  main:  # can be footer , also
  - name: Home
    pageRef: /
    weight: 10
  - name: About
    pageRef: /about
    weight: 20
  - name: Services
    pageRef: /services
    weight: 30

# copied : not applicable ?
summaryLength: 25
copyright : "John Doe - All rights reserved"
enableEmoji : true
# publishDir : "docs"
